baseurl: ''
lang: en-US
timezone: Europe/Lisbon
theme: jekyll-theme-chirpy

title: Gustavo Bonito
tagline: Security Researcher
description: Full-Time Penetration Tester, Security Researcher, Bug Hunter. Offensive Security Certified Professional (OSCP)

url: 'https://gustavobonito.pt'
author: Gustavo Bonito 
github:
  username: gBon1to
twitter:
  username: gBon1to

social:
  name: Gustavo Bonito
  links:
    - https://github.com/gBon1to
    - https://twitter.com/gBon1to
    - https://www.linkedin.com/in/gBon1to

#google_site_verification: google_meta_tag_verification

google_analytics:
  id: 'UA-182648705-1'
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false

theme_mode: dark
img_cdn: ''
avatar: assets/img/profile.jpg

toc: true

disqus:
  comments: false
  shortname: ''

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /posts/:title/

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
